// Mock Ingredients Catalog ตามโครงสร้าง ER Diagram Section 4
// บันทึกสารอาหารหลัก (Macronutrients) มาตรฐานในหน่วยต่อ 100 กรัม (basisWeightG: 100)

export const ingredients = {
  // --- กลุ่มเนื้อสัตว์ & โปรตีน (Meat, Poultry, Seafood, Protein) ---
  ing_pork_mince: {
    _id: "ing_pork_mince",
    nameTh: "หมูสับอนามัย",
    nameEn: "Minced Pork",
    category: "meat",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 263,
      protein: 17.0,
      carbs: 0.0,
      fat: 21.0,
      fiber: 0.0,
      sodium: 65,
    },
    allergens: [],
    isActive: true,
  },
  ing_pork_belly: {
    _id: "ing_pork_belly",
    nameTh: "หมูสามชั้น",
    nameEn: "Pork Belly",
    category: "meat",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 518,
      protein: 9.3,
      carbs: 0.0,
      fat: 53.0,
      fiber: 0.0,
      sodium: 32,
    },
    allergens: [],
    isActive: true,
  },
  ing_chicken_drumstick: {
    _id: "ing_chicken_drumstick",
    nameTh: "น่องไก่สด",
    nameEn: "Chicken Drumstick",
    category: "poultry",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 172,
      protein: 28.3,
      carbs: 0.0,
      fat: 5.7,
      fiber: 0.0,
      sodium: 86,
    },
    allergens: [],
    isActive: true,
  },
  ing_chicken_breast: {
    _id: "ing_chicken_breast",
    nameTh: "เนื้ออกไก่ลอกหนัง",
    nameEn: "Chicken Breast Fillet",
    category: "poultry",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 165,
      protein: 31.0,
      carbs: 0.0,
      fat: 3.6,
      fiber: 0.0,
      sodium: 74,
    },
    allergens: [],
    isActive: true,
  },
  ing_beef_shank: {
    _id: "ing_beef_shank",
    nameTh: "เนื้อวัวน่องลาย",
    nameEn: "Beef Shank",
    category: "meat",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 201,
      protein: 34.0,
      carbs: 0.0,
      fat: 6.2,
      fiber: 0.0,
      sodium: 55,
    },
    allergens: [],
    isActive: true,
  },
  ing_shrimp: {
    _id: "ing_shrimp",
    nameTh: "กุ้งสดแกะเปลือก",
    nameEn: "Fresh Shrimp",
    category: "seafood",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 99,
      protein: 24.0,
      carbs: 0.2,
      fat: 0.3,
      fiber: 0.0,
      sodium: 111,
    },
    allergens: ["shellfish", "crustacean"],
    isActive: true,
  },
  ing_squid: {
    _id: "ing_squid",
    nameTh: "ปลาหมึกกล้วย",
    nameEn: "Squid Rings",
    category: "seafood",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 92,
      protein: 15.6,
      carbs: 3.1,
      fat: 1.4,
      fiber: 0.0,
      sodium: 44,
    },
    allergens: ["molluscs"],
    isActive: true,
  },
  ing_sea_bass: {
    _id: "ing_sea_bass",
    nameTh: "เนื้อปลากะพงขาว",
    nameEn: "Sea Bass Fillet",
    category: "seafood",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 97,
      protein: 18.4,
      carbs: 0.0,
      fat: 2.0,
      fiber: 0.0,
      sodium: 68,
    },
    allergens: ["fish"],
    isActive: true,
  },
  ing_tofu_firm: {
    _id: "ing_tofu_firm",
    nameTh: "เต้าหู้ขาวแข็ง",
    nameEn: "Firm Tofu",
    category: "protein",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 83,
      protein: 10.0,
      carbs: 1.9,
      fat: 5.3,
      fiber: 1.0,
      sodium: 12,
    },
    allergens: ["soy"],
    isActive: true,
  },
  ing_egg: {
    _id: "ing_egg",
    nameTh: "ไข่ไก่สด",
    nameEn: "Fresh Chicken Egg",
    category: "dairy_egg",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 143,
      protein: 12.6,
      carbs: 0.7,
      fat: 9.5,
      fiber: 0.0,
      sodium: 142,
    },
    allergens: ["egg"],
    isActive: true,
  },

  // --- กลุ่มผัก สมุนไพร และเครื่องเทศ (Vegetables, Herbs & Spices) ---
  ing_tomato_cherry: {
    _id: "ing_tomato_cherry",
    nameTh: "มะเขือเทศสีดา",
    nameEn: "Cherry Tomatoes",
    category: "vegetable",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sodium: 5,
    },
    allergens: [],
    isActive: true,
  },
  ing_chili_jinda: {
    _id: "ing_chili_jinda",
    nameTh: "พริกขี้หนูจินดา",
    nameEn: "Bird's Eye Red Chili",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 40,
      protein: 1.9,
      carbs: 8.8,
      fat: 0.4,
      fiber: 1.5,
      sodium: 9,
    },
    allergens: [],
    isActive: true,
  },
  ing_garlic_thai: {
    _id: "ing_garlic_thai",
    nameTh: "กระเทียมไทยแกะกลีบ",
    nameEn: "Thai Garlic Cloves",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 149,
      protein: 6.4,
      carbs: 33.1,
      fat: 0.5,
      fiber: 2.1,
      sodium: 17,
    },
    allergens: [],
    isActive: true,
  },
  ing_shallot: {
    _id: "ing_shallot",
    nameTh: "หอมแดงซอย",
    nameEn: "Sliced Shallots",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 72,
      protein: 2.5,
      carbs: 16.8,
      fat: 0.1,
      fiber: 3.2,
      sodium: 12,
    },
    allergens: [],
    isActive: true,
  },
  ing_lemongrass: {
    _id: "ing_lemongrass",
    nameTh: "ตะไคร้ซอย",
    nameEn: "Lemongrass Stalks",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 99,
      protein: 1.8,
      carbs: 25.3,
      fat: 0.5,
      fiber: 4.2,
      sodium: 6,
    },
    allergens: [],
    isActive: true,
  },
  ing_galangal: {
    _id: "ing_galangal",
    nameTh: "ข่าแก่หั่นแว่น",
    nameEn: "Sliced Galangal",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 71,
      protein: 1.0,
      carbs: 15.0,
      fat: 1.0,
      fiber: 2.0,
      sodium: 5,
    },
    allergens: [],
    isActive: true,
  },
  ing_kaffir_leaf: {
    _id: "ing_kaffir_leaf",
    nameTh: "ใบมะกรูดฉีก",
    nameEn: "Kaffir Lime Leaves",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 45,
      protein: 2.8,
      carbs: 7.5,
      fat: 0.5,
      fiber: 3.0,
      sodium: 10,
    },
    allergens: [],
    isActive: true,
  },
  ing_sweet_basil: {
    _id: "ing_sweet_basil",
    nameTh: "ใบโหระพา",
    nameEn: "Sweet Basil",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 23,
      protein: 3.2,
      carbs: 2.7,
      fat: 0.6,
      fiber: 1.6,
      sodium: 4,
    },
    allergens: [],
    isActive: true,
  },
  ing_holy_basil: {
    _id: "ing_holy_basil",
    nameTh: "ใบกะเพราป่า",
    nameEn: "Holy Basil Leaves",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 22,
      protein: 3.1,
      carbs: 2.7,
      fat: 0.6,
      fiber: 1.6,
      sodium: 4,
    },
    allergens: [],
    isActive: true,
  },
  ing_mint: {
    _id: "ing_mint",
    nameTh: "ใบสะระแหน่",
    nameEn: "Fresh Mint Leaves",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 44,
      protein: 3.3,
      carbs: 8.4,
      fat: 0.7,
      fiber: 6.8,
      sodium: 31,
    },
    allergens: [],
    isActive: true,
  },
  ing_culantro: {
    _id: "ing_culantro",
    nameTh: "ผักชีฝรั่ง",
    nameEn: "Sawtooth Coriander / Culantro",
    category: "herb_spice",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 25,
      protein: 2.0,
      carbs: 4.0,
      fat: 0.5,
      fiber: 2.5,
      sodium: 15,
    },
    allergens: [],
    isActive: true,
  },
  ing_green_papaya: {
    _id: "ing_green_papaya",
    nameTh: "มะละกอดิบสับเส้น",
    nameEn: "Shredded Green Papaya",
    category: "vegetable",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 39,
      protein: 0.6,
      carbs: 9.8,
      fat: 0.1,
      fiber: 1.8,
      sodium: 3,
    },
    allergens: [],
    isActive: true,
  },
  ing_string_bean: {
    _id: "ing_string_bean",
    nameTh: "ถั่วฝักยาว",
    nameEn: "Yardlong Beans",
    category: "vegetable",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 47,
      protein: 2.8,
      carbs: 8.4,
      fat: 0.4,
      fiber: 3.6,
      sodium: 4,
    },
    allergens: [],
    isActive: true,
  },
  ing_thai_eggplant: {
    _id: "ing_thai_eggplant",
    nameTh: "มะเขือเปราะ",
    nameEn: "Thai Round Eggplant",
    category: "vegetable",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 25,
      protein: 1.0,
      carbs: 5.8,
      fat: 0.2,
      fiber: 3.0,
      sodium: 2,
    },
    allergens: [],
    isActive: true,
  },
  ing_morning_glory: {
    _id: "ing_morning_glory",
    nameTh: "ผักบุ้งจีน",
    nameEn: "Morning Glory / Water Spinach",
    category: "vegetable",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 19,
      protein: 2.6,
      carbs: 3.1,
      fat: 0.2,
      fiber: 2.1,
      sodium: 113,
    },
    allergens: [],
    isActive: true,
  },
  ing_bamboo_shoot: {
    _id: "ing_bamboo_shoot",
    nameTh: "หน่อไม้ต้ม",
    nameEn: "Boiled Bamboo Shoot",
    category: "vegetable",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 27,
      protein: 2.6,
      carbs: 5.2,
      fat: 0.3,
      fiber: 2.2,
      sodium: 4,
    },
    allergens: [],
    isActive: true,
  },

  // --- กลุ่มคาร์โบไฮเดรต เส้น และกะทิ (Carbs, Noodles & Coconut) ---
  ing_egg_noodle: {
    _id: "ing_egg_noodle",
    nameTh: "บะหมี่ไข่เส้นแบน",
    nameEn: "Flat Egg Noodles",
    category: "carb",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 280,
      protein: 10.2,
      carbs: 54.8,
      fat: 2.5,
      fiber: 2.0,
      sodium: 180,
    },
    allergens: ["gluten", "egg"],
    isActive: true,
  },
  ing_rice_noodle: {
    _id: "ing_rice_noodle",
    nameTh: "เส้นก๋วยเตี๋ยว / ขนมจีน",
    nameEn: "Rice Noodles",
    category: "carb",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 109,
      protein: 1.9,
      carbs: 24.9,
      fat: 0.2,
      fiber: 0.8,
      sodium: 12,
    },
    allergens: [],
    isActive: true,
  },
  ing_glass_noodle: {
    _id: "ing_glass_noodle",
    nameTh: "วุ้นเส้นถั่วเขียวแท้",
    nameEn: "Mung Bean Glass Noodles",
    category: "carb",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 351,
      protein: 0.2,
      carbs: 86.0,
      fat: 0.1,
      fiber: 0.5,
      sodium: 15,
    },
    allergens: [],
    isActive: true,
  },
  ing_coconut_milk: {
    _id: "ing_coconut_milk",
    nameTh: "หัวกะทิคั้นสด 100%",
    nameEn: "Fresh Coconut Milk",
    category: "coconut",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 230,
      protein: 2.3,
      carbs: 5.5,
      fat: 23.8,
      fiber: 2.2,
      sodium: 15,
    },
    allergens: [],
    isActive: true,
  },

  // --- กลุ่มเครื่องปรุงรส น้ำพริก และซอส (Seasonings, Pastes & Sauces) ---
  ing_curry_paste_khao_soi: {
    _id: "ing_curry_paste_khao_soi",
    nameTh: "พริกแกงข้าวซอยสูตรเมืองเหนือ",
    nameEn: "Northern Khao Soi Curry Paste",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 118,
      protein: 3.5,
      carbs: 16.2,
      fat: 4.3,
      fiber: 5.2,
      sodium: 1650,
    },
    allergens: [],
    isActive: true,
  },
  ing_curry_paste_hung_lay: {
    _id: "ing_curry_paste_hung_lay",
    nameTh: "พริกแกงฮังเลและผงฮังเล",
    nameEn: "Hung Lay Curry Paste & Masala Spice",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 135,
      protein: 4.1,
      carbs: 18.0,
      fat: 5.2,
      fiber: 6.0,
      sodium: 1720,
    },
    allergens: [],
    isActive: true,
  },
  ing_curry_paste_green: {
    _id: "ing_curry_paste_green",
    nameTh: "พริกแกงเขียวหวานตำสด",
    nameEn: "Fresh Green Curry Paste",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 112,
      protein: 3.2,
      carbs: 14.8,
      fat: 4.1,
      fiber: 5.5,
      sodium: 1850,
    },
    allergens: ["shrimp"],
    isActive: true,
  },
  ing_curry_paste_southern_sour: {
    _id: "ing_curry_paste_southern_sour",
    nameTh: "พริกแกงส้มใต้ขมิ้นสด",
    nameEn: "Southern Sour Turmeric Curry Paste",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 95,
      protein: 2.8,
      carbs: 15.5,
      fat: 2.1,
      fiber: 4.8,
      sodium: 1950,
    },
    allergens: ["shrimp"],
    isActive: true,
  },
  ing_curry_paste_massaman: {
    _id: "ing_curry_paste_massaman",
    nameTh: "พริกแกงมัสมั่นเครื่องเทศเทศ",
    nameEn: "Massaman Curry Paste",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 142,
      protein: 3.8,
      carbs: 17.5,
      fat: 6.3,
      fiber: 5.8,
      sodium: 1680,
    },
    allergens: ["shrimp", "peanut"],
    isActive: true,
  },
  ing_fish_sauce: {
    _id: "ing_fish_sauce",
    nameTh: "น้ำปลาแท้เกรดพรีเมียม",
    nameEn: "Premium Fish Sauce",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 35,
      protein: 6.0,
      carbs: 2.5,
      fat: 0.0,
      fiber: 0.0,
      sodium: 7200,
    },
    allergens: ["fish"],
    isActive: true,
  },
  ing_palm_sugar: {
    _id: "ing_palm_sugar",
    nameTh: "น้ำตาลมะพร้าวอัมพวา",
    nameEn: "Pure Coconut Palm Sugar",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 380,
      protein: 0.2,
      carbs: 95.0,
      fat: 0.1,
      fiber: 0.0,
      sodium: 40,
    },
    allergens: [],
    isActive: true,
  },
  ing_tamarind_paste: {
    _id: "ing_tamarind_paste",
    nameTh: "น้ำมะขามเปียกคั้นเข้มข้น",
    nameEn: "Concentrated Tamarind Paste",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 239,
      protein: 2.8,
      carbs: 62.5,
      fat: 0.6,
      fiber: 5.1,
      sodium: 28,
    },
    allergens: [],
    isActive: true,
  },
  ing_lime_juice: {
    _id: "ing_lime_juice",
    nameTh: "น้ำมะนาวแท้คั้นสด",
    nameEn: "Fresh Squeezed Lime Juice",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 25,
      protein: 0.4,
      carbs: 8.4,
      fat: 0.1,
      fiber: 0.4,
      sodium: 2,
    },
    allergens: [],
    isActive: true,
  },
  ing_pla_ra: {
    _id: "ing_pla_ra",
    nameTh: "น้ำปลาร้าต้มสุกปรุงรส",
    nameEn: "Cooked Fermented Fish Sauce",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 45,
      protein: 7.5,
      carbs: 3.0,
      fat: 0.3,
      fiber: 0.0,
      sodium: 5800,
    },
    allergens: ["fish"],
    isActive: true,
  },
  ing_roasted_rice_powder: {
    _id: "ing_roasted_rice_powder",
    nameTh: "ข้าวคั่วหอมกลิ่นใบมะกรูด",
    nameEn: "Toasted Rice Powder",
    category: "seasoning",
    basisWeightG: 100,
    nutrientsPer100g: {
      calories: 360,
      protein: 7.5,
      carbs: 78.0,
      fat: 1.5,
      fiber: 3.2,
      sodium: 5,
    },
    allergens: [],
    isActive: true,
  },
};

export default ingredients;
